# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: migreazy 2.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "migreazy".freeze
  s.version = "2.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Francis Hwang".freeze]
  s.date = "2017-10-06"
  s.description = "migreazy helps manage Rails migrations across git branches.".freeze
  s.email = "sera@fhwang.net".freeze
  s.executables = ["migreazy".freeze]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/migreazy",
    "lib/migreazy.rb",
    "migreazy.gemspec"
  ]
  s.homepage = "http://github.com/fhwang/migreazy".freeze
  s.rubygems_version = "2.5.2".freeze
  s.summary = "migreazy helps manage Rails migrations across git branches.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rugged>.freeze, ["~> 0.26.0"])
    else
      s.add_dependency(%q<rugged>.freeze, ["~> 0.26.0"])
    end
  else
    s.add_dependency(%q<rugged>.freeze, ["~> 0.26.0"])
  end
end

